name: Create Releases
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Npm install
        uses: ./.github/actions
      - run: npx nx affected -t test build --parallel=3 --exclude='json-api-front,json-api-server,json-api-server-e2e,json-shared-type,database,@nestjs-json-api/source' --base=origin/master
      - run: npx nx affected -t upload-badge --parallel=3 --exclude='json-api-front,json-api-server,shared-utils,json-api-server-e2e,json-shared-type,database,@nestjs-json-api/source' --base=origin/master
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
  #      - run: npm nx affected -t e2e-ci --parallel=1
  #      - run: npm nx affected -t deploy --no-agents

  bump-version:
    name: "Bump version"
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      actions: "read"
      id-token: "write"
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout and install
        uses: ./.github/actions
      - name: Bump version
        run: |
          git config user.name 'Alex H'
          git config user.email 'klerick666@gmail.com'
          npx nx release --skip-publish --dry-run
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
