name: CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore cached npm dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: ${{ runner.os }}-npm-dependencies-${{ hashFiles('package-lock.json') }}
      - run:  npm ci
      - name: Cache npm dependencies
        id: cache-dependencies-save
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "main"
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main
      - run: npx nx affected -t lint test build --parallel=3 --exclude='test-npm'
#      - run: npm nx affected -t e2e-ci --parallel=1
#      - run: npm nx affected -t deploy --no-agents
